title: Andre's Site for ENGL 5995
email: cincospenguinos@gmail.com
description: >-
  This is my site--er, "Content Management System" for ENGLISH 5995, Digital Humanities.
  I'll be putting all sorts of things on here, I suppose.
baseurl: "/ENGL5995" # the subpath of your site, e.g. /blog
url: "https://cincospenguinos.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andreCLaFleur
github_username:  cincospenguinos

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
exclude:
  - '.gitignore'
  - 'README.md'